name             "apptentive_kafka"
maintainer       "Apptentive, Inc."
maintainer_email "engineering@apptentive.com"
license          "mit"
description      "Installs and configures kafka"
long_description "Installs and configures kafka"
version          "0.3.2"

depends "runit", "~> 1.5.14"
depends "ulimit", "~> 0.3"
